In [1]:
import numpy as np
from copy import deepcopy
from scipy import ndimage

In [2]:
grid1 = [[np.nan,np.nan,4,np.nan,np.nan,np.nan,np.nan],
         [np.nan,np.nan,np.nan,6,np.nan,np.nan,np.nan],
         [5,np.nan,np.nan,np.nan,np.nan,np.nan,np.nan],
         [np.nan,3,np.nan,np.nan,np.nan,6,np.nan],
         [np.nan,np.nan,np.nan,np.nan,np.nan,np.nan,2],
         [np.nan,np.nan,np.nan,1,np.nan,np.nan,np.nan],
         [np.nan,np.nan,np.nan,np.nan,4,np.nan,np.nan]]
grid1 = np.matrix(grid1)
print(grid1)

topfirst1 =    [5,4,None,None,None,7,5]
bottomfirst1 = [5,7,None,None,None,3,6]
leftfirst1 =   [5,7,None,None,None,5,7]
rightfirst1 =  [7,4,None,None,None,7,6]

[[nan nan  4. nan nan nan nan]
 [nan nan nan  6. nan nan nan]
 [ 5. nan nan nan nan nan nan]
 [nan  3. nan nan nan  6. nan]
 [nan nan nan nan nan nan  2.]
 [nan nan nan  1. nan nan nan]
 [nan nan nan nan  4. nan nan]]


In [3]:
grid2 = [[np.nan,2,np.nan,np.nan,np.nan,np.nan,np.nan],
         [2,np.nan,np.nan,np.nan,np.nan,np.nan,np.nan],
         [np.nan,np.nan,np.nan,np.nan,np.nan,np.nan,np.nan],
         [np.nan,np.nan,np.nan,np.nan,np.nan,3,np.nan],
         [np.nan,np.nan,np.nan,np.nan,3,np.nan,np.nan],
         [np.nan,np.nan,np.nan,3,np.nan,np.nan,np.nan],
         [np.nan,np.nan,np.nan,np.nan,np.nan,np.nan,1]]
grid2 = np.matrix(grid2)
print(grid2)

topfirst2 =    [None,None,5,6,None,6,7]
bottomfirst2 = [6,7,5,None,None,None,None]
leftfirst2 =   [None,None,5,6,None,7,6]
rightfirst2 =  [6,6,4,None,None,None,None]

[[nan  2. nan nan nan nan nan]
 [ 2. nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan]
 [nan nan nan nan nan  3. nan]
 [nan nan nan nan  3. nan nan]
 [nan nan nan  3. nan nan nan]
 [nan nan nan nan nan nan  1.]]


In [4]:
grid3 = [[np.nan,np.nan,np.nan,np.nan,4,np.nan,np.nan],
         [np.nan,6,np.nan,np.nan,np.nan,np.nan,np.nan],
         [4,np.nan,np.nan,np.nan,np.nan,np.nan,6],
         [np.nan,np.nan,np.nan,np.nan,np.nan,np.nan,np.nan],
         [6,np.nan,np.nan,np.nan,np.nan,np.nan,4],
         [np.nan,np.nan,np.nan,np.nan,np.nan,6,np.nan],
         [np.nan,np.nan,4,np.nan,np.nan,np.nan,np.nan]]
grid3 = np.matrix(grid3)
print(grid3)

topfirst3 =    [7,None,None,5,None,7,None]
bottomfirst3 = [None,7,None,3,None,None,5]
leftfirst3 =   [None,None,None,7,None,None,None]
rightfirst3 =  [None,None,None,5,None,None,None]

[[nan nan nan nan  4. nan nan]
 [nan  6. nan nan nan nan nan]
 [ 4. nan nan nan nan nan  6.]
 [nan nan nan nan nan nan nan]
 [ 6. nan nan nan nan nan  4.]
 [nan nan nan nan nan  6. nan]
 [nan nan  4. nan nan nan nan]]


In [5]:
grid4 = [[np.nan,np.nan,np.nan,np.nan,np.nan,np.nan,np.nan],
         [np.nan,np.nan,np.nan,np.nan,np.nan,np.nan,np.nan],
         [np.nan,np.nan,np.nan,np.nan,np.nan,np.nan,3],
         [np.nan,np.nan,np.nan,np.nan,np.nan,np.nan,np.nan],
         [np.nan,np.nan,np.nan,np.nan,4,np.nan,np.nan],
         [np.nan,np.nan,np.nan,np.nan,np.nan,np.nan,np.nan],
         [np.nan,np.nan,3,np.nan,np.nan,np.nan,np.nan]]
grid4 = np.matrix(grid4)
print(grid4)

topfirst4 =    [None,None,None,None,None,None,None]
bottomfirst4 = [None,6,None,5,None,4,None]
leftfirst4 =   [1,2,3,4,5,6,7]
rightfirst4 =  [None,6,None,4,None,2,None]

[[nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan  3.]
 [nan nan nan nan nan nan nan]
 [nan nan nan nan  4. nan nan]
 [nan nan nan nan nan nan nan]
 [nan nan  3. nan nan nan nan]]


In [6]:
def possible(yn,xn,n,originalgrid,topfirst,bottomfirst,leftfirst,rightfirst):    
        
    #Create a copy of the original grid
    grid = deepcopy(originalgrid)
    
    #Insert new val
    grid.itemset((yn, xn), n)
    
    #If there are no nan, check sum of row and col
    if not np.isnan(grid[yn]).any():
        if grid[yn].sum() != 20:
            return False
    

    if not np.isnan(grid[:,xn]).any():
        if grid[:,xn].sum() != 20:
            return False
        
    #Check if new val is allowed by top/bottom/left/right first
    if topfirst[xn] != None:
        for el in grid[:,xn]:
            if np.isnan(el) or el == topfirst[xn]:
                break
            elif el == 0:
                continue
            else:
                return False
            
    if bottomfirst[xn] != None:
        for el in reversed(grid[:,xn]):
            if np.isnan(el) or el == bottomfirst[xn]:
                break
            elif el == 0:
                continue
            else:
                return False
            
    if leftfirst[yn] != None:
        for el in grid[yn].T:
            if np.isnan(el) or el == leftfirst[yn]:
                break
            elif el == 0:
                continue
            else:
                return False
            
    if rightfirst[yn] != None:
        for el in reversed(grid[yn].T):
            if np.isnan(el) or el == rightfirst[yn]:
                break
            elif el == 0:
                continue
            else:
                return False
        
    #After the first checks for nan, replace nan with zeros
    grid[np.isnan(grid)] = 0
    grid = grid.astype(int)
    
    #Putting a zeros is almost always ok
    if n == 0:
        return True
    
    #Check if there are no more than n val equal to n
    if np.count_nonzero(grid == n) > n:
        return False
    
    #Check if new val creates row / col with sum 20 and count 4 
    if grid[yn].sum() > 20 or np.count_nonzero(grid[yn]) > 4:
        return False
    if grid[:,xn].sum() > 20 or np.count_nonzero(grid[:,xn]) > 4:
        return False
    
    #Check neighbouring squares
    grid = grid.tolist()
    try: #Top left square
        topleftcorner = grid[yn-1][xn-1]
        top = grid[yn-1][xn]
        left = grid[yn][xn-1]
        if topleftcorner != 0 and top != 0 and left != 0:
            return False
    except IndexError:
        pass
    
    try: #Top right square
        toprightcorner = grid[yn-1][xn+1]
        top = grid[yn-1][xn]
        right = grid[yn][xn+1]
        if toprightcorner != 0 and top != 0 and right != 0:
            return False
    except IndexError:
        pass
    
    try: #Bottom left square
        bottomleftcorner = grid[yn+1][xn-1]
        bottom = grid[yn+1][xn]
        left = grid[yn][xn-1]
        if bottomleftcorner != 0 and bottom != 0 and left != 0:
            return False
    except IndexError:
        pass
    
    try: #Bottom right square
        bottomrightcorner = grid[yn+1][xn+1]
        bottom = grid[yn+1][xn]
        left = grid[yn][xn+1]
        if bottomrightcorner != 0 and bottom != 0 and right != 0:
            return False
    except IndexError:
        pass 
        
    #If the number passes all selections return True
    return True    

In [7]:
def solve(grid,topfirst,bottomfirst,leftfirst,rightfirst):
    
    for y in range(7):
        for x in range(7):
            if np.isnan(grid.item((y,x))):
                for n in reversed(range(0,8)):
                    if possible(y,x,n,grid,topfirst,bottomfirst,leftfirst,rightfirst):
                        grid.itemset((y, x), n)
                        sol = solve(grid,topfirst,bottomfirst,leftfirst,rightfirst)
                        try:
                            if sol == None:
                                pass
                        except ValueError:
                            return sol  
                        grid.itemset((y, x), np.nan)
                return 
    
    #Check whether the grid is a fully-connected island
    _ , numberfeatures = ndimage.label(grid)
    if numberfeatures == 1:
        return grid

In [8]:
g1 = deepcopy(grid1)
sol1 = solve(g1,topfirst1,bottomfirst1,leftfirst1,rightfirst1)
print(sol1)

[[5. 4. 4. 0. 0. 7. 0.]
 [0. 0. 7. 6. 3. 4. 0.]
 [5. 6. 2. 0. 7. 0. 0.]
 [0. 3. 0. 0. 6. 6. 5.]
 [5. 7. 0. 6. 0. 0. 2.]
 [5. 0. 7. 1. 0. 0. 7.]
 [0. 0. 0. 7. 4. 3. 6.]]


In [9]:
g2 = deepcopy(grid2)
sol2 = solve(g2,topfirst2,bottomfirst2,leftfirst2,rightfirst2)
print(sol2)

[[7. 2. 5. 6. 0. 0. 0.]
 [2. 0. 0. 5. 7. 6. 0.]
 [5. 7. 4. 0. 0. 4. 0.]
 [0. 0. 6. 0. 4. 3. 7.]
 [6. 4. 0. 0. 3. 0. 7.]
 [0. 7. 5. 3. 0. 0. 5.]
 [0. 0. 0. 6. 6. 7. 1.]]


In [10]:
g3 = deepcopy(grid3)
sol3 = solve(g3,topfirst3,bottomfirst3,leftfirst3,rightfirst3)
print(sol3)

[[7. 2. 0. 0. 4. 7. 0.]
 [0. 6. 7. 5. 2. 0. 0.]
 [4. 5. 0. 5. 0. 0. 6.]
 [0. 0. 0. 7. 7. 1. 5.]
 [6. 7. 3. 0. 0. 0. 4.]
 [3. 0. 6. 0. 0. 6. 5.]
 [0. 0. 4. 3. 7. 6. 0.]]


In [11]:
g4 = deepcopy(grid4)
sol4 = solve(g4,topfirst4,bottomfirst4,leftfirst4,rightfirst4)
print(sol4)

[[0. 0. 0. 1. 5. 7. 7.]
 [0. 2. 5. 7. 0. 0. 6.]
 [3. 7. 0. 7. 0. 0. 3.]
 [4. 0. 0. 0. 5. 7. 4.]
 [0. 5. 6. 5. 4. 0. 0.]
 [6. 0. 6. 0. 6. 2. 0.]
 [7. 6. 3. 0. 0. 4. 0.]]


In [12]:
solution = sol1 + sol2 + sol3 + sol4
print(solution)

[[19.  8.  9.  7.  9. 21.  7.]
 [ 2.  8. 19. 23. 12. 10.  6.]
 [17. 25.  6. 12.  7.  4.  9.]
 [ 4.  3.  6.  7. 22. 17. 21.]
 [17. 23.  9. 11.  7.  0. 13.]
 [14.  7. 24.  4.  6.  8. 17.]
 [ 7.  6.  7. 16. 17. 20.  7.]]


In [13]:
tot = 0
for y in range(7):
    for x in range(7):
        tot += pow(solution.item(y,x),2)
print(tot)

8520.0
